{"name": "testcase2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n  +2\n  -3", "trace": "@pytest.mark.run(order=2)\n    @allure.title(\"testcase2\")\n    @allure.description(\"I am first test_case2\")\n    @allure.story('story_2')\n    @allure.severity(\"blocker\")\n    def test_case2():\n        print('I am case2')\n        LoggerForApitest.writeInfoLog(\"I AM CASE2\")\n>       assert 2 == 3\nE       assert 2 == 3\nE         +2\nE         -3\n\npytest_case\\test_fixtures1.py:53: AssertionError"}, "description": "I am first test_case2", "attachments": [{"name": "log", "source": "8e914030-9729-474c-8229-35f6c08d4944-attachment.txt", "type": "text/plain"}], "start": 1648007253050, "stop": 1648007253051, "uuid": "8f9ca78f-fd8e-4156-b4ed-201ad580156e", "historyId": "92f9d3b642298a60c88279ecf235fa2d", "testCaseId": "725ce7cbcf31b4144284ab868efa6e15", "fullName": "pytest_case.test_fixtures1#test_case2", "labels": [{"name": "severity", "value": "blocker"}, {"name": "story", "value": "story_2"}, {"name": "tag", "value": "run(order=2)"}, {"name": "parentSuite", "value": "pytest_case"}, {"name": "suite", "value": "test_fixtures1"}, {"name": "host", "value": "no-delecs-g42-test-wx405299"}, {"name": "thread", "value": "8268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_case.test_fixtures1"}]}